version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mushcase_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mushcase
      MYSQL_USER: mushcase_user
      MYSQL_PASSWORD: mushcase_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mushcase_backend
    environment:
      DB_HOST: mysql
      DB_USER: mushcase_user
      DB_PASSWORD: mushcase_pass
      DB_NAME: mushcase
      JWT_SECRET: super_secret_jwt_key_for_mushcase
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mushcase_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data: